name: interaction
description: Social events with a focus on safety and acceptance.
publish_to: 'none'
version: 0.0.0-a1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
